language: objective-c
os: osx
env:
  global:
  - PROJECT="Brine.xcodeproj"
  - IOS_SDK=iphonesimulator12.0
  - MACOS_SDK=macosx10.14

matrix:
  include:
    - osx_image: xcode10.0beta
      env:
        - DESTINATION="OS=11.3,name=iPhone 8 Plus"
        - SCHEME="Brine-iOS"
        - SDK="$IOS_SDK"
        - XCODEBUILD_COMMAND="test"
        - PLATFORM="iOS"
    - osx_image: xcode9.3
      env:
        - DESTINATION="platform=macOS,arch=x86_64"
        - SCHEME="Brine-macOS"
        - SDK="$MACOS_SDK"
        - XCODEBUILD_COMMAND="build-for-testing"
        - PLATFORM="macOS"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - travis_retry xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES "$XCODEBUILD_COMMAND" | xcpretty;
  - travis_retry carthage build --no-skip-current --platform "$PLATFORM"
