language: objective-c
os: osx
env:
  global:
  - PROJECT="Brine.xcodeproj"
  - IOS_SDK=iphonesimulator11.3
  - MACOS_SDK=macosx10.13

matrix:
  include:
    - osx_image: xcode9.3
      env:
        - DESTINATION="OS=11.3,name=iPhone 8 Plus"
        - SCHEME="Brine-iOS"
        - SDK="$IOS_SDK"
    - osx_image: xcode9.3
      env:
        - DESTINATION="platform=macOS,arch=x86_64"
        - SCHEME="Brine-macOS"
        - SDK="$MACOS_SDK"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - travis_retry xcodebuild -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
