language: objective-c
os: osx
env:
  global:
  - PROJECT="Brine.xcodeproj"
  - IOS_SDK=iphonesimulator11.3
  - BRINE_FRAMEWORK_IOS_SCHEME="Brine"
  - BRINE_EXAMPLE_IOS_SCHEME="BrineExample"

matrix:
  include:
    - osx_image: xcode9.3
      env:
        - DESTINATION="OS=11.3,name=iPhone 8 Plus"
        - SCHEME="$BRINE_FRAMEWORK_IOS_SCHEME"
        - SDK="$IOS_SDK"
        - EXAMPLE_SCHEME="$BRINE_EXAMPLE_IOS_SCHEME"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - travis_retry xcodebuild \
      -project "$PROJECT" \
      -scheme "$SCHEME" \
      -sdk "$SDK" \
      -destination "$DESTINATION" \
      -configuration Debug \
      ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
  - travis_retry xcodebuild \
      -project "$PROJECT" \
      -scheme "$EXAMPLE_SCHEME" \
      -sdk "$SDK" \
      -destination "$DESTINATION" \
      -configuration Debug \
      ONLY_ACTIVE_ARCH=NO build | xcpretty;
